
package javaee.spectacle.webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18 Wed Mar 16 20:44:57 CET 2016 Generated source
 * version: 2.7.18
 */

@XmlRootElement(name = "reserverSpectacleResponse",
    namespace = "http://webservices.spectacle.javaee/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reserverSpectacleResponse", namespace = "http://webservices.spectacle.javaee/")

public class ReserverSpectacleResponse {

  @XmlElement(name = "return")
  private int _return;

  public int getReturn() {
    return this._return;
  }

  public void setReturn(int new_return) {
    this._return = new_return;
  }

}

