
package javaee.spectacle.webservices.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18 Wed Mar 16 20:44:57 CET 2016 Generated source
 * version: 2.7.18
 */

@XmlRootElement(name = "reserverSpectacle", namespace = "http://webservices.spectacle.javaee/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reserverSpectacle", namespace = "http://webservices.spectacle.javaee/")

public class ReserverSpectacle {

  @XmlElement(name = "arg0")
  private javaee.spectacle.beans.Reservation arg0;

  public javaee.spectacle.beans.Reservation getArg0() {
    return this.arg0;
  }

  public void setArg0(javaee.spectacle.beans.Reservation newArg0) {
    this.arg0 = newArg0;
  }

}

